version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password!
      POSTGRES_DB: postgres-db
    restart: always
    networks:
      - postgres
networks:
  postgres:
