name: Deploy Swagger to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci

      - name: Generate Swagger YAML
        run: |
          export GENERATE_SWAGGER_YAML=true
          npm run start

      # PRの場合はswagger.yamlをアーティファクトとして保存
      - name: Upload swagger.yaml as an artifact
        if: contains(github.event_name, 'pull_request')
        uses: actions/upload-artifact@v4
        with:
          name: swagger-yaml
          path: docs/swagger.yaml

      # mainブランチへのpushの場合のみGitHub Pagesにデプロイ
      - name: Upload artifact for GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    if: github.event_name == 'push' # pull_request 時はデプロイしない
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
